FROM debian:bookworm-slim

RUN apt update && apt install -y cyrus-imapd net-tools

EXPOSE 25 143 465 993 4190 8080

HEALTHCHECK --interval=5s --retries=10 CMD netstat -ltn | grep -c :143 || exit 1

COPY --chmod=755 entrypoint.sh /usr/local/sbin/

CMD /usr/local/sbin/entrypoint.sh